package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sort_expander",
    srcs = ["sort_expander.cc"],
    hdrs = ["sort_expander.h"],
    deps = [
        "//metal_pjrt/compiler:report_bug",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "@xla//xla:comparison_util",
        "@xla//xla:literal_util",
        "@xla//xla:shape_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/pass:hlo_pass",
        "@xla//xla/service:hlo_creation_utils",
        "@xla//xla/tsl/platform:errors",
        "@xla//xla/tsl/platform:statusor",
    ],
)

cc_test(
    name = "sort_expander_test",
    srcs = ["sort_expander_test.cc"],
    deps = [
        ":sort_expander",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
        "@xla//xla:literal",
        "@xla//xla:literal_util",
        "@xla//xla:shape_util",
        "@xla//xla/hlo/evaluator:hlo_evaluator",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/testlib:hlo_hardware_independent_test_base",
    ],
)

cc_library(
    name = "scan_rewriter",
    srcs = ["scan_rewriter.cc"],
    hdrs = ["scan_rewriter.h"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@xla//xla:literal",
        "@xla//xla:literal_util",
        "@xla//xla:shape_util",
        "@xla//xla:window_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/pass:hlo_pass",
        "@xla//xla/service/gpu:backend_configs_cc",
        "@xla//xla/tsl/platform:errors",
        "@xla//xla/tsl/platform:statusor",
    ],
)

cc_library(
    name = "conv_rewriter",
    srcs = ["conv_rewriter.cc"],
    hdrs = ["conv_rewriter.h"],
    deps = [
        "//metal_pjrt/conv",
        "@com_google_absl//absl/algorithm:container",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@xla//xla:permutation_util",
        "@xla//xla:shape_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/pass:hlo_pass",
        "@xla//xla/service/gpu:backend_configs_cc",
        "@xla//xla/tsl/platform:errors",
        "@xla//xla/tsl/platform:statusor",
    ],
)

cc_test(
    name = "ffi_rewriters_test",
    srcs = ["ffi_rewriters_test.cc"],
    deps = [
        ":conv_rewriter",
        ":scan_rewriter",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
        "@xla//xla:shape_util",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/testlib:hlo_hardware_independent_test_base",
        "@xla//xla/service/gpu:backend_configs_cc",
    ],
)

cc_library(
    name = "dot_upcast",
    srcs = ["dot_upcast.cc"],
    hdrs = ["dot_upcast.h"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@xla//xla:shape_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/pass:hlo_pass",
        "@xla//xla/tsl/platform:errors",
    ],
)

cc_test(
    name = "dot_upcast_test",
    srcs = ["dot_upcast_test.cc"],
    deps = [
        ":dot_upcast",
        "@com_google_googletest//:gtest_main",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/testlib:hlo_hardware_independent_test_base",
    ],
)

cc_library(
    name = "hlo_checks",
    srcs = ["hlo_checks.cc"],
    hdrs = ["hlo_checks.h"],
    deps = [
        "//metal_pjrt/compiler:report_bug",
        ":dot_upcast",
        "//metal_pjrt/blas:blas_lt_support",
        "@com_google_absl//absl/algorithm:container",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/types:span",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@xla//xla:shape_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/service/gpu:backend_configs_cc",
        "@xla//xla/service/gpu:cublas_cudnn",
        "@xla//xla/service/gpu:matmul_utils",
        "@xla//xla/stream_executor:device_description",
        "@xla//xla/tsl/platform:statusor",
    ],
)

cc_test(
    name = "hlo_checks_test",
    srcs = ["hlo_checks_test.cc"],
    deps = [
        ":dot_upcast",
        ":hlo_checks",
        "//metal_pjrt/blas:blas_lt_support",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/hlo/ir:hlo",
        "@xla//xla/hlo/testlib:hlo_hardware_independent_test_base",
        "@xla//xla/stream_executor/gpu:gpu_blas_lt",
    ],
)
