#!/usr/bin/env python3
# Copyright 2026 The metal-pjrt-plugin Authors
# SPDX-License-Identifier: Apache-2.0

"""Generate the license notices for the code statically linked into the
plugin dylib (XLA and its dependencies).

third_party/notices_manifest.json lists every third-party project with code
in the dylib and where its license text lives under Bazel's external directory
(the pinned sources). For each this prints a header block (project, URL,
version, SPDX id, user) and the license text, verbatim.

  scripts/gen_third_party_notices.py EXTERNAL_DIR            # to stdout
  scripts/gen_third_party_notices.py EXTERNAL_DIR -o FILE
  scripts/gen_third_party_notices.py EXTERNAL_DIR --update   # THIRD_PARTY_NOTICES

EXTERNAL_DIR is "$(bazel info output_base)/external" of a checkout that has
built the plugin; this script never runs bazel. --update keeps the
hand-written top of THIRD_PARTY_NOTICES (everything above the line of 79 "=")
and replaces the rest.

A license item in the manifest is {"path"} (whole file), {"path", "lines":
[first, last]} (a license that exists only as a source-file header) or
{"text", "origin"} (the pinned archive ships no license file). "expect" is a
string the item must contain (required). A missing file or a failed "expect" exits 1:
that is how a pin bump that moves or changes a license gets noticed. Entries
marked "handwritten" have their section in the top part; only their files are
checked here.
"""
import json, pathlib, sys, textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "third_party" / "notices_manifest.json"
NOTICES = ROOT / "THIRD_PARTY_NOTICES"
RULE, DIVIDER = "-" * 79, "=" * 79
FIELDS = [("version", "Version"), ("source", "Source"), ("spdx", "License"),
          ("used_by", "Used by"), ("note", "Note")]


def die(msg):
    sys.exit(f"gen_third_party_notices: {msg}")


def license_text(item, external, name):
    """(label, text) of one license item of project `name`."""
    if "text" in item:
        label, text = item["origin"], "\n".join(item["text"]) + "\n"
    else:
        path = external / item["path"]
        if not path.is_file():
            die(f"{name}: {path} not found; update {MANIFEST.relative_to(ROOT)}")
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as e:
            die(f"{name}: {path} is not UTF-8 ({e})")
        label = item["path"].split("/", 1)[1]  # without the Bazel repo directory
        if "lines" in item:
            first, last = item["lines"]
            text = "\n".join(text.split("\n")[first - 1:last]) + "\n"
            label += f", lines {first}-{last}"
    if not text.strip() or item["expect"] not in text:
        die(f"{name}: {label} is empty or lacks {item['expect']!r}; "
            f"update {MANIFEST.relative_to(ROOT)}")
    return label, text


def section(p, external):
    out = [RULE, f"{p['name']} ({p['url']})", RULE, ""]
    for key, label in FIELDS:
        if p.get(key):
            out.append(textwrap.fill(f"{label}: {p[key]}", 79, subsequent_indent="  ",
                                     break_long_words=False, break_on_hyphens=False))
    if not p.get("license"):
        die(f"{p['name']}: no license listed")
    for kind in ("license", "notice"):
        for item in p.get(kind, []):
            label, text = license_text(item, external, p["name"])
            out += ["", f"[{kind}: {label}]", "", text.strip("\n")]
    return "\n".join(out) + "\n"


def generate(external):
    projects = json.loads(MANIFEST.read_text(encoding="utf-8"))["projects"]
    out = [DIVIDER, "Statically linked projects",
           "(generated by scripts/gen_third_party_notices.py from",
           "third_party/notices_manifest.json; do not edit below this line)", DIVIDER, ""]
    for p in projects:
        where = "  [above]" if p.get("handwritten") else ""
        out.append(f"  {p['name']}: {p['spdx']}{where}")
    out.append("")
    for p in projects:
        if p.get("handwritten"):
            for item in p.get("license", []):
                license_text(item, external, p["name"])
        else:
            out += ["", section(p, external)]
    return "\n".join(out)


def main(argv):
    argv, out = list(argv), None
    if "-o" in argv[:-1]:
        i = argv.index("-o")
        out = pathlib.Path(argv[i + 1])
        del argv[i:i + 2]
    update = "--update" in argv
    argv = [a for a in argv if a != "--update"]
    if len(argv) != 1 or argv[0].startswith("-") or (update and out):
        print(__doc__.strip(), file=sys.stderr)
        return 2
    external = pathlib.Path(argv[0])
    if not external.is_dir():
        die(f"{external} is not a directory")
    text = generate(external)
    if update:
        out = NOTICES
        head = out.read_text(encoding="utf-8").split(DIVIDER + "\n", 1)[0].rstrip("\n")
        text = head + "\n\n\n" + text
    if out:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out} ({text.count(chr(10))} lines, {len(text.encode())} bytes)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
