# Copyright 2026 The metal-pjrt-plugin Authors
# SPDX-License-Identifier: Apache-2.0

"""embed_msl: a .metal file as a NUL-terminated char array in a header.

The kernels are compiled at run time (MTLDevice newLibraryWithSource; the
Xcode command-line tools have no offline `metal` compiler), so their source
has to be in the dylib. Being part of the image, it is covered by the dylib's
LC_UUID, which keys the compilation cache.

  embed_msl(name = "scan", src = "scan.metal", symbol = "kScanMsl")

makes `scan.metal.h`, declaring

  namespace metal_pjrt::kernels { inline constexpr char kScanMsl[] = {...}; }

and the cc_library `name` exporting it.
"""

def embed_msl(name, src, symbol, visibility = None):
    out = src + ".h"
    guard = "METAL_PJRT_KERNELS_" + out.upper().replace(".", "_").replace("/", "_") + "_"
    native.genrule(
        name = name + "_embed",
        srcs = [src],
        outs = [out],
        cmd = "\n".join([
            "{",
            "echo '// Generated by embed_msl from $<. Do not edit.'",
            "echo '#ifndef " + guard + "'",
            "echo '#define " + guard + "'",
            "echo 'namespace metal_pjrt::kernels {'",
            "echo 'inline constexpr char " + symbol + "[] = {'",
            "od -An -v -tx1 $< | sed -e 's/ *\\([0-9a-f][0-9a-f]\\)/0x\\1,/g'",
            "echo '0x00};'",
            "echo '}  // namespace metal_pjrt::kernels'",
            "echo '#endif'",
            "} > $@",
        ]),
    )
    native.cc_library(
        name = name,
        hdrs = [out],
        visibility = visibility,
    )
